# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42c0d24e26b023a0195027a8685604c171f3a9e155f6339fc63576a1ecd85dd2b60e42bb5478d0cdb54826ef54a19c0423094b6f9bb04c57cefa9e6f26cb9c24

test:
  secret_key_base: b6037b8be0c461c37e3e7b777d74d4327218e6a6aeff49ddd554c3ea0a70df9ddc5829bbbe8bc05627ff273685cbc3eaf34ab95fe8ec01ca382adc53141aed41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
